"""Recruiter-facing dashboard: Black-Scholes surfaces, dataset coverage, and
the autograd validation story. Run from the repo root:

    uv run --extra app streamlit run app/dashboard.py
"""

import math

import plotly.graph_objects as go
import streamlit as st
import torch
from plotly.subplots import make_subplots

from dhps.bench.evaluate import evaluate_learner, greeks_curve, ood_metrics
from dhps.bench.speed import mc_paths_for_error, payoff_std, price_one_option_mc, time_fn
from dhps.datasets.european import FEATURES, LABELS, make_european_dataset
from dhps.hedging.policy import DeepHedgeConfig, train_deep_hedge
from dhps.hedging.simulator import cvar, delta_positions, hedge_pnl, premium_bs
from dhps.pricing.aad import bs_greeks_ad
from dhps.pricing.black_scholes import bs_greeks, bs_price
from dhps.pricing.pathwise_mc import pathwise_european_greeks
from dhps.simulators.gbm import simulate_gbm
from dhps.train.trainer import TrainConfig, train_model

st.set_page_config(page_title="DHPS — Pricing & Differential ML", layout="wide")

TEMPLATE = "plotly_white"
GREEKS = ("delta", "gamma", "vega", "theta", "rho")
GREEK_TITLES = {
    "delta": "Delta (∂V/∂S)", "gamma": "Gamma (∂²V/∂S²)", "vega": "Vega (∂V/∂σ)",
    "theta": "Theta (−∂V/∂T, per year)", "rho": "Rho (∂V/∂r)",
}


# ---------------------------------------------------------------- overview --

def render_overview() -> None:
    st.header("Deep Hedging & Pricing Simulator")
    st.markdown(
        """
European options priced and risk-managed three independent ways, forced to
agree: **analytic Black-Scholes**, **autograd (AAD)**, and **pathwise Monte
Carlo** (Greeks by backpropagating through simulated paths). On top of
that, two models train live in this dashboard: a **differential ML pricer**
(Savine) and a **deep-hedging policy** under transaction costs (Buehler).
Pick a page above — every chart is computed live from this repo's library.
        """
    )
    st.subheader("Benchmark status")
    cols = st.columns(4)
    cols[0].metric("Pricer & Greeks", "3 independent routes",
                   "agree to 1e-13", delta_color="off")
    cols[1].metric("DML pricer", "price MAE 0.05",
                   "2.4x better than baseline", delta_color="off")
    cols[2].metric("Inference speed", "0.8 µs/price",
                   "~100,000x faster than MC", delta_color="off")
    cols[3].metric("Deep hedging", "beats delta under costs",
                   "CVaR95 -3.6 vs -4.2", delta_color="off")
    st.caption(
        "Tolerances are statistical: Monte Carlo gates use CLT bands, "
        "autograd gates use 1e-10 absolute error. Full numbers and plots in "
        "reports/benchmarks/, regenerated by scripts/benchmark.py."
    )


# ------------------------------------------------------------------ pricer --

def render_pricer() -> None:
    st.header("Pricer & Greeks explorer")
    st.markdown(
        "Closed-form prices and Greeks across a spot grid. Deal parameters "
        "in the sidebar; curves recompute live."
    )
    with st.sidebar:
        st.subheader("Deal parameters")
        strike = st.slider("Strike K", 50.0, 150.0, 100.0, 1.0)
        t_mat = st.slider("Maturity T (years)", 0.1, 2.0, 1.0, 0.05)
        sigma = st.slider("Volatility σ", 0.05, 0.6, 0.2, 0.01)
        rate = st.slider("Risk-free rate r", 0.0, 0.10, 0.05, 0.005)
        div = st.slider("Dividend yield q", 0.0, 0.06, 0.01, 0.005)
        is_call = st.toggle("Call (off = put)", value=True)

    spots = torch.linspace(50.0, 150.0, 401, dtype=torch.float64)
    price = bs_price(spots, strike, rate, div, sigma, t_mat, call=is_call)
    greeks = bs_greeks(spots, strike, rate, div, sigma, t_mat, call=is_call)

    k_col, atm_col, delta_col, gamma_col = st.columns(4)
    spot_atm = float(spots[200])
    atm = float(bs_price(torch.tensor([spot_atm]), strike, rate, div, sigma,
                         t_mat, call=is_call)[0])
    # live no-arbitrage self-check: |P - C - (K e^{-rT} - S e^{-qT})|
    other = float(bs_price(torch.tensor([spot_atm]), strike, rate, div, sigma,
                           t_mat, call=not is_call)[0])
    parity_gap = abs(other - atm - (strike * math.exp(-rate * t_mat)
                                    - spot_atm * math.exp(-div * t_mat)))
    k_col.metric("Parity gap (self-check)", f"{parity_gap:.1e}",
                 "put-call identity", delta_color="off")
    atm_col.metric(f"Price at S={spot_atm:.0f}", f"{atm:.4f}")
    delta_col.metric(f"Delta at S={spot_atm:.0f}",
                     f"{float(greeks['delta'][200]):.4f}")
    gamma_col.metric(f"Gamma at S={spot_atm:.0f}",
                     f"{float(greeks['gamma'][200]):.4f}")

    fig = make_subplots(rows=2, cols=3,
                        subplot_titles=("Value", *(GREEK_TITLES[g] for g in GREEKS)))
    fig.add_trace(go.Scatter(x=spots.tolist(), y=price.tolist(), showlegend=False), 1, 1)
    for i, g in enumerate(GREEKS):
        fig.add_trace(go.Scatter(x=spots.tolist(), y=greeks[g].tolist(),
                                 showlegend=False), 1 + (i + 1) // 3, (i + 1) % 3 + 1)
    fig.update_layout(height=560, template=TEMPLATE, title_text="Value and Greeks vs spot")
    st.plotly_chart(fig, width="stretch")

    st.subheader("Value surface over spot and volatility")
    vol_grid = torch.linspace(0.05, 0.6, 56, dtype=torch.float64)
    mesh_s, mesh_v = torch.meshgrid(spots[::4], vol_grid, indexing="ij")
    surface = bs_price(mesh_s, strike, rate, div, mesh_v, t_mat, call=is_call)
    heat = go.Figure(go.Heatmap(x=vol_grid.tolist(), y=spots[::4].tolist(),
                                z=surface.tolist(), colorscale="Viridis"))
    heat.update_xaxes(title_text="volatility σ")
    heat.update_yaxes(title_text="spot")
    heat.update_layout(height=480, template=TEMPLATE)
    st.plotly_chart(heat, width="stretch")


# ----------------------------------------------------------------- dataset --

@st.cache_data(show_spinner="Building dataset...")
def _build_dataset(n_samples: int, seed: int) -> dict[str, torch.Tensor]:
    return make_european_dataset(n_samples=n_samples, seed=seed)


def render_dataset() -> None:
    st.header("Training data")
    st.markdown(
        "Scrambled-Sobol coverage of the parameter space — spot, moneyness, "
        "maturity, volatility — with analytic price and Greek labels for "
        "every sample. This is the dataset the differential ML model will "
        "train on."
    )
    with st.sidebar:
        st.subheader("Dataset")
        n_samples = st.slider("Samples", 10_000, 200_000, 50_000, step=10_000)
        seed = st.slider("Seed", 1, 99, 7)
    data = _build_dataset(n_samples, seed)

    n_tr = data["x_train"].shape[0]
    n_va = data["x_val"].shape[0]
    c1, c2, c3 = st.columns(3)
    c1.metric("Train samples", f"{n_tr:,}")
    c2.metric("Val samples", f"{n_va:,}")
    c3.metric("Features / labels", f"{len(FEATURES)} / {len(LABELS)}")
    st.caption(
        f"features: {', '.join(FEATURES)} — value labels: {', '.join(LABELS)} "
        "— plus gradient labels d(price)/d(feature) that drive differential "
        "training (see the Learned pricer page)"
    )

    left, right = st.columns(2)
    with left:
        st.subheader("Parameter coverage")
        idx = torch.randperm(n_tr)[:4000]
        xs = data["x_train"][idx]
        scat = go.Figure(go.Scatter(
            x=xs[:, 0].tolist(), y=xs[:, 3].tolist(),
            mode="markers", marker=dict(size=4, color=xs[:, 0] / xs[:, 1],
                                        colorscale="Viridis", showscale=True,
                                        colorbar=dict(title="moneyness s0/K")),
        ))
        scat.update_xaxes(title_text="spot")
        scat.update_yaxes(title_text="volatility")
        scat.update_layout(height=440, template=TEMPLATE)
        st.plotly_chart(scat, width="stretch")
    with right:
        st.subheader("Notes")
        st.markdown(
            "Labels come from the closed-form pricer — no simulation noise. "
            "Color = moneyness s0/K. The train/val split depends only on the "
            "seed, so runs are comparable."
        )

    st.subheader("Label distributions (one panel per label)")
    st.caption(
        "The spikes at exactly 0 (and 1 for delta) are real, not numerical "
        "noise: the sampler includes deep-OTM/deep-ITM corners where the "
        "normal CDF saturates to exactly 1.0 and gamma/vega underflow to "
        "exactly 0.0 in float64."
    )
    fig = make_subplots(rows=2, cols=3, subplot_titles=list(LABELS))
    for j in range(len(LABELS)):
        fig.add_trace(go.Histogram(x=data["y_train"][:, j].tolist(),
                                   histnorm="probability density",
                                   showlegend=False), 1 + j // 3, j % 3 + 1)
    fig.update_layout(height=560, template=TEMPLATE)
    st.plotly_chart(fig, width="stretch")


# ------------------------------------------------------------------- model --

def render_model() -> None:
    st.header("Differential ML: the learned pricer")
    st.markdown(
        "Two identical networks, same data: **baseline** sees prices only, "
        "**DML** also sees the price gradients. Both train live in this "
        "session; every chart below is the resulting model."
    )
    if "dml_result" not in st.session_state:
        with st.spinner("Training both learners (~40 s)..."):
            cfg = TrainConfig(n_samples=20_000, hidden=(64, 64, 64),
                              epochs=300, batch_size=8_192, seed=7)
            st.session_state.dml_result = train_model(cfg, differential=True)
            st.session_state.base_result = train_model(cfg, differential=False)
            st.session_state.train_data = make_european_dataset(
                n_samples=20_000, seed=7)
    dml = st.session_state.dml_result
    base = st.session_state.base_result
    data = st.session_state.train_data

    m_d, m_b = evaluate_learner(dml, data), evaluate_learner(base, data)
    o_d, o_b = ood_metrics(dml), ood_metrics(base)
    c1, c2 = st.columns(2)
    c1.metric("Delta MAE — DML vs baseline",
              f"{m_d['delta_mae']:.4f} vs {m_b['delta_mae']:.4f}",
              f"{(1 - m_d['delta_mae'] / m_b['delta_mae']) * 100:.0f}% better")
    c2.metric("Price MAE — DML vs baseline",
              f"{m_d['price_mae']:.4f} vs {m_b['price_mae']:.4f}",
              f"{(1 - m_d['price_mae'] / m_b['price_mae']) * 100:.0f}% better")
    st.caption(
        "Out-of-distribution check (spots 25-45, 210-240, outside training "
        f"range): DML price MAE {o_d['ood_price_mae']:.3f} vs baseline "
        f"{o_b['ood_price_mae']:.3f}. At this live budget extrapolation is "
        "unreliable for both — OOD claims belong to the full-budget "
        "benchmark, not a demo."
    )

    with st.sidebar:
        st.subheader("Curve configuration")
        strike = st.slider("Curve strike K", 70.0, 130.0, 100.0, 5.0)
        t_mat = st.slider("Curve maturity T", 0.25, 2.0, 1.0, 0.25)
        sigma = st.slider("Curve volatility", 0.05, 0.6, 0.2, 0.05)

    # keep the spot sweep inside the training box: moneyness K/S in [0.6, 1.4]
    s_lo, s_hi = strike / 1.4, strike / 0.6
    spots = torch.linspace(max(50.0, s_lo), min(200.0, s_hi), 300,
                           dtype=torch.float64)
    curves = {"DML": greeks_curve(dml, spots, strike, t_mat, sigma),
              "baseline": greeks_curve(base, spots, strike, t_mat, sigma)}
    tab_delta, tab_gamma = st.tabs(["Delta", "Gamma (not a label)"])
    for tab, greek in ((tab_delta, "delta"), (tab_gamma, "gamma")):
        fig = go.Figure()
        ref = curves["DML"]
        fig.add_trace(go.Scatter(x=spots.tolist(), y=ref[f"{greek}_true"].tolist(),
                                 name="analytic", line=dict(dash="dash", width=3)))
        for name, c in curves.items():
            fig.add_trace(go.Scatter(x=spots.tolist(), y=c[greek].tolist(),
                                     name=name, line=dict(width=2)))
        if greek == "delta":  # no-arbitrage bounds for a vanilla's delta
            fig.add_hline(y=0.0, line_dash="dot", line_color="gray")
            fig.add_hline(y=1.0, line_dash="dot", line_color="gray")
        fig.update_xaxes(title_text="spot")
        fig.update_yaxes(title_text=greek)
        fig.update_layout(height=460, template=TEMPLATE)
        tab.plotly_chart(fig, width="stretch")
    st.info(
        "Gamma is not a training label — it comes from a second autograd "
        "pass through the trained network."
    )

    st.subheader("Speed vs Monte Carlo")
    st.caption(
        "Same accuracy, different cost: the trained net prices a batch in "
        "microseconds; Monte Carlo is timed at the path count its CLT error "
        "needs to match this model's price accuracy."
    )

    if "speed" not in st.session_state:
        with st.spinner("Timing inference vs Monte Carlo..."):
            p_std = payoff_std()
            n_matched = mc_paths_for_error(p_std, m_d["price_mae"])
            xs = torch.randn(100_000, 4, dtype=torch.float64)
            model = st.session_state.dml_result.model

            def batch():
                with torch.no_grad():
                    model(xs)

            t_batch = time_fn(batch)
            t_mc = time_fn(lambda: price_one_option_mc(n_matched), repeats=3)
            st.session_state.speed = {
                "n": n_matched, "batch_us": t_batch * 1e6 / 100_000,
                "mc_us": t_mc * 1e6}
    spd = st.session_state.speed
    k1, k2, k3 = st.columns(3)
    k1.metric("DML, batched 100k", f"{spd['batch_us']:.2f} µs/price")
    k2.metric(f"Monte Carlo ({spd['n']:,} paths)",
              f"{spd['mc_us']:,.0f} µs/price")
    k3.metric("Speed-up at matched error",
              f"{spd['mc_us'] / spd['batch_us']:,.0f}x")


# --------------------------------------------------------------- hedging ---

@st.cache_data(show_spinner="Training the deep-hedging policy (~20 s)...")
def _hedge_results(cost: float) -> dict:
    """Train the policy at this cost level and score every strategy on the
    SAME eval paths. Returns plain floats/lists for caching."""
    cfg = DeepHedgeConfig(n_paths=8_192, n_steps=26, cost_rate=cost,
                          epochs=80, seed=7, eval_paths=4_096)
    res = train_deep_hedge(cfg)
    sim = dict(s0=cfg.s0, r=cfg.r, q=cfg.q, sigma=cfg.sigma,
               t_maturity=cfg.t_maturity)
    paths = simulate_gbm(n_paths=cfg.eval_paths, n_steps=cfg.n_steps,
                         antithetic=True, seed=cfg.eval_seed, **sim)
    premium = premium_bs(cfg.s0, cfg.strike, cfg.r, cfg.q, cfg.sigma,
                         cfg.t_maturity)
    delta = delta_positions(paths, cfg.strike, cfg.r, cfg.q, cfg.sigma,
                            cfg.t_maturity)

    def pnl_of(positions: torch.Tensor) -> torch.Tensor:
        return hedge_pnl(paths, cfg.strike, premium, positions, cost)

    strats = {"no hedge": pnl_of(torch.zeros_like(delta)),
              "delta (weekly)": pnl_of(delta),
              "deep hedge (policy)": res.eval_pnl}
    out = {"pnl": {}, "stats": {}, "volume": {}}
    for name, pnl in strats.items():
        out["pnl"][name] = pnl.tolist()
        out["stats"][name] = {"mean": float(pnl.mean()), "std": float(pnl.std()),
                              "cvar95": cvar(pnl)}
    trades_d = torch.cat([delta[:, :1], delta[:, 1:] - delta[:, :-1]], dim=1)
    out["volume"]["delta (weekly)"] = float(trades_d.abs().sum(1).mean())
    out["volume"]["deep hedge (policy)"] = res.metrics["traded_volume"]
    out["train_seconds"] = res.seconds
    return out


def render_hedging() -> None:
    st.header("Deep hedging under transaction costs")
    st.markdown(
        "The book: SHORT one at-the-money call (premium ~9.83), stock traded "
        "at 26 dates over a year. Weekly delta is the classical rule; the "
        "policy network is trained on tail risk through simulated "
        "trajectories. Same paths, costs, premium — only the trading rule "
        "differs."
    )
    # percent units end to end: the slider reads in %, the model gets a fraction
    cost_pct = st.sidebar.slider("Transaction cost rate", 0.0, 2.0, 1.0, 0.25,
                                 format="%.2f%%")
    cost = cost_pct / 100.0
    data = _hedge_results(cost)
    names = list(data["pnl"])

    cols = st.columns(3)
    for col, name in zip(cols, names, strict=True):
        s = data["stats"][name]
        col.metric(f"{name} — CVaR95", f"{s['cvar95']:.2f}",
                   f"mean {s['mean']:+.2f} · std {s['std']:.2f}",
                   delta_color="off")
    st.caption(
        "CVaR95 = average P&L of the worst 5% of simulated years (higher is "
        "better; negative is normal — it is a LOSS measure, not profit). "
        "Hedging does NOT create profit: the option is priced fairly, so "
        "expected P&L is ~0 by construction. The game is paying less for the "
        "same protection — the policy's edge is cost efficiency, not alpha."
    )

    st.info(
        "**How to read the charts.** Each simulated year produces one P&L "
        "number. In the distribution plot: wide = many years there, the dot "
        "is the median year, the box is the middle 50%, whiskers reach to "
        "the disasters. std is spread around the average, NOT a typical win: "
        "no hedge has std 15 around an average of ≈ 0 — years land anywhere "
        "from +10 to −50."
    )

    colors = {"no hedge": "#636EFA", "delta (weekly)": "#EF553B",
              "deep hedge (policy)": "#00CC96"}
    fig = go.Figure()
    for name in names:
        fig.add_trace(go.Violin(y=data["pnl"][name], name=name,
                                line_color=colors[name], box_visible=True,
                                meanline_visible=True, points=False,
                                spanmode="hard"))
    fig.add_hline(y=0.0, line_dash="dot", line_color="gray")
    fig.update_layout(height=520, template=TEMPLATE,
                      title_text="P&L distribution per strategy "
                                 "(dot = median, box = middle 50%)")
    fig.update_yaxes(title_text="P&L of one simulated year ($)")
    st.plotly_chart(fig, width="stretch")

    s = data["stats"]
    n_years = len(data["pnl"]["no hedge"])
    spike_share = sum(1 for x in data["pnl"]["no hedge"] if x > 9.0) / n_years
    st.markdown(
        f"**No hedge is not profitable.** In ~{spike_share:.0%} of years the "
        f"call expires worthless and the seller keeps the ~9.8 premium — but "
        f"rally years lose without bound, so the average year is "
        f"{s['no hedge']['mean']:+.2f}, below delta "
        f"({s['delta (weekly)']['mean']:+.2f}) and the policy "
        f"({s['deep hedge (policy)']['mean']:+.2f}), and the worst 5% of "
        f"years average {s['no hedge']['cvar95']:.1f}. Hedging gives up the "
        f"good years to delete the bad ones."
    )

    st.subheader("Chance of losing more than L in a year")
    st.caption(
        "Pick a loss L on the x-axis; the curve gives the probability that "
        "the year loses MORE than L. Lower is safer. Where each curve starts "
        "at L=0 is that strategy's chance of a losing year at all; where it "
        "crosses the 5% line is its worst-5% loss (the cards' CVaR95 is the "
        "average beyond that point)."
    )
    fig_cdf = go.Figure()
    x_max = 0.0
    for name in names:
        pnl_sorted = torch.sort(torch.tensor(data["pnl"][name])).values
        losses = -pnl_sorted  # ascending P&L -> descending loss; worst year first
        probs = (torch.arange(1, n_years + 1, dtype=torch.float64)
                 / n_years * 100.0)
        x_max = max(x_max, float(losses.max()))
        fig_cdf.add_trace(go.Scatter(x=losses.tolist(), y=probs.tolist(),
                                     name=name, line=dict(color=colors[name],
                                                          width=2.5)))
    fig_cdf.add_hline(y=5.0, line_dash="dash", line_color="gray")
    fig_cdf.update_xaxes(title_text="loss L ($)")
    fig_cdf.update_yaxes(
        title_text="probability of losing more than L (%)",
        type="log",
        range=[math.log10(100.0 / n_years) - 0.15, 2.05],
        tickvals=[0.1, 0.5, 1, 2, 5, 10, 25, 50, 100],
        ticktext=["0.1%", "0.5%", "1%", "2%", "5%", "10%", "25%", "50%",
                  "100%"],
    )
    fig_cdf.update_xaxes(range=[0, x_max * 1.02])
    fig_cdf.update_layout(height=460, template=TEMPLATE)
    st.plotly_chart(fig_cdf, width="stretch")

    vol = data["volume"]
    st.markdown(
        f"**Traded volume** (avg Σ|Δ position| per path): delta "
        f"{vol['delta (weekly)']:.2f} vs policy "
        f"{vol['deep hedge (policy)']:.2f} — the policy trades less where "
        "delta is flat and acts near the strike."
    )
    st.caption(
        f"Policy retrained live in {data['train_seconds']:.0f} s at this "
        "cost level. P&L is undiscounted — same simplification for every "
        "strategy."
    )


# -------------------------------------------------------------- validation --

def render_validation() -> None:
    st.header("Validation: three roads to the same Greek")
    st.markdown(
        "The core claim of this repo, checked live: **derivatives come free "
        "from autograd**. The analytic formulas, autograd through the pricer, "
        "and backprop through Monte Carlo paths must agree."
    )

    st.subheader("Autograd vs analytic formulas")
    spots = torch.linspace(60.0, 150.0, 91, dtype=torch.float64)
    ad = bs_greeks_ad(spots, 100.0, 0.05, 0.01, 0.2, 1.0)
    an = bs_greeks(spots, 100.0, 0.05, 0.01, 0.2, 1.0)
    worst = max(float((ad[g] - an[g]).abs().max()) for g in GREEKS)
    m1, m2 = st.columns(2)
    m1.metric("Max abs error, all 5 Greeks", f"{worst:.2e}")
    m2.metric("Agreement", "bit-level (float64)" if worst < 1e-10 else "CHECK")
    st.caption(
        "Same pricer, two differentiation strategies: hand-derived formulas "
        "vs torch.autograd.grad. Any disagreement here would be a bug in one "
        "of them."
    )

    st.subheader("Pathwise Monte Carlo vs analytic delta")
    st.markdown(
        "Delta estimated by backpropagating through 100,000 simulated GBM "
        "paths at each spot, with ±2 standard-error bands. The estimator is "
        "unbiased — the analytic curve must sit inside the bands."
    )
    with st.sidebar:
        st.subheader("Pathwise MC")
        pw_strike = st.slider("Strike (MC)", 70.0, 130.0, 100.0, 5.0)
        pw_sigma = st.slider("Volatility (MC)", 0.05, 0.6, 0.2, 0.05)
        pw_t = st.slider("Maturity (MC)", 0.25, 2.0, 1.0, 0.25)
        pw_n = st.select_slider("Paths per point", (10_000, 50_000, 100_000, 200_000))

    @st.cache_data(show_spinner="Running pathwise Monte Carlo...")
    def _pw_curve(strike: float, sigma: float, t_mat: float, n_paths: int):
        pts = []
        for s0 in (80.0, 85.0, 90.0, 95.0, 100.0, 105.0, 110.0, 115.0, 120.0):
            res = pathwise_european_greeks(
                n_paths=n_paths, n_steps=64, s0=s0, strike=strike, r=0.05,
                q=0.01, sigma=sigma, t_maturity=t_mat, seed=11,
            )
            pts.append((s0, res["delta"], 2 * res["delta_se"]))
        return pts

    pts = _pw_curve(pw_strike, pw_sigma, pw_t, pw_n)
    curve_spots = torch.linspace(75.0, 125.0, 201, dtype=torch.float64)
    analytic = bs_greeks(curve_spots, pw_strike, 0.05, 0.01, pw_sigma, pw_t)["delta"]
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=curve_spots.tolist(), y=analytic.tolist(),
                             name="analytic delta", line=dict(width=3)))
    fig.add_trace(go.Scatter(
        x=[p[0] for p in pts], y=[p[1] for p in pts],
        error_y=dict(type="data", array=[p[2] for p in pts], visible=True),
        name="pathwise MC ± 2·SE", mode="markers", marker=dict(size=9),
    ))
    fig.update_xaxes(title_text="spot")
    fig.update_yaxes(title_text="delta")
    fig.update_layout(height=480, template=TEMPLATE)
    st.plotly_chart(fig, width="stretch")

    st.info(
        "**Why no Monte Carlo gamma?** The call payoff has a kink at the "
        "strike: its second derivative is a Dirac delta, and autograd through "
        "`clamp` returns zero almost everywhere. The pathwise gamma estimator "
        "is invalid, not merely noisy — likelihood-ratio or Malliavin weights "
        "would be needed. Excluding it is a correctness decision, not a "
        "shortcut."
    )


# --------------------------------------------------------------------- run --

PAGES = {
    "Overview": render_overview,
    "Pricer & Greeks": render_pricer,
    "Training data": render_dataset,
    "Learned pricer (DML)": render_model,
    "Deep hedging": render_hedging,
    "Validation": render_validation,
}


def nav_bar() -> str:
    """Top nav bar of plain buttons; the active page is highlighted.

    Clicks must be read from ``st.session_state`` BEFORE the buttons are
    created: widget state updates before the rerun, while the button's
    return value only arrives at creation time — too late to set its own
    ``type`` on the click run, which left the highlight one rerun behind.
    """
    current = st.session_state.get("page", next(iter(PAGES)))
    for name in PAGES:
        if st.session_state.get(f"nav_{name}"):
            current = name
    st.session_state.page = current
    cols = st.columns(len(PAGES))
    for col, name in zip(cols, PAGES, strict=True):
        col.button(name, key=f"nav_{name}",
                   type="primary" if name == current else "secondary",
                   width="stretch")
    return current


page = nav_bar()
PAGES[page]()
